# Generated by Django 4.1.4 on 2023-01-14 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follwer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_follower', to=settings.AUTH_USER_MODEL)),
                ('follwing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_following', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
