# Generated by Django 4.1.4 on 2023-01-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Profile',
        ),
    ]
