# Generated by Django 4.1.4 on 2023-01-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_rename_follow_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follwing',
            new_name='following',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follwer',
        ),
    ]
