# Generated by Django 4.1.4 on 2023-01-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_post_like_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like_post',
            new_name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
